name: Format, Analyze and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  default_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: Install and set Flutter version
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter analyze lib
      - run: flutter test --no-pub --coverage

      - name: Upload coverage to codecov
      - run: curl -s https://codecov.io/bash
      - shell: bash
        with:
          fail_ci_if_error: true